### ISSUE TITLE
Scanning a device throws System.BadImageException

### ISSUE THREAD

**Issue by 0verflux** [dotnet-bluetooth-le/dotnet-bluetooth-le#723]
App crashes when trying to call `StartScanningForDevicesAsync`. 
I first checked the following permissions in manifest: `BLUETOOTH`, `BLUETOOTH_ADMIN`, `BLUETOOTH_CONNECT`, `BLUETOOTH_SCAN`, and the app runs normally, but no devices are returned. I then added two permissions: `ACCESSCOARSE_LOCATION` and `ACCESSFINE_LOCATION` and rerun the app, the app stops responding and an error `System.BadImageException` is thrown.

## Steps to reproduce

1.  add permission `ACCESSCOARSE_LOCATION` or `ACCESSFINE_LOCATION` in manifest file

2. run the app

3. grant Location permission

4. start scanning for devices

5. app stops responding

## Expected behavior
App should run normally and show devices found

## Actual behavior
Exception is thrown: System.BadImageException : Read out of bounds

### Crashlog

```
[ViewRootImpl@cbf43b8[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@cbf43b8[MainActivity]] ViewPostIme pointer 1
[BluetoothAdapter] STATE_ON
[BluetoothAdapter] STATE_ON
[BluetoothAdapter] STATE_ON
[BluetoothAdapter] STATE_ON
[BluetoothAdapter] STATE_ON
[BluetoothLeScanner] Start Scan with callback
[BluetoothLeScanner] onScannerRegistered() - status=0 scannerId=12 mScannerId=0
[BluetoothAdapter] BluetoothAdapter() : com.companyname.automatedmedicinebox.ui
[monodroid-assembly] open_from_bundles: failed to load assembly System.Core.dll
Read out of bounds.
System.BadImageFormatException: Read out of bounds.
   at System.Reflection.Throw.OutOfBounds()
   at System.Reflection.Metadata.Ecma335.MethodDebugInformationTableReader.GetDocument(MethodDebugInformationHandle handle)
   at Mono.Debugging.Soft.PortablePdbData.GetDebugInfoFromPdb(MethodMirror method) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\PortablePdbData.cs:line 186
   at Mono.Debugging.Soft.SoftDebuggerBacktrace.CreateStackFrame(StackFrame frame, Int32 frameIndex) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerBacktrace.cs:line 157
   at Mono.Debugging.Soft.SoftDebuggerBacktrace.GetStackFrames(Int32 firstIndex, Int32 lastIndex) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerBacktrace.cs:line 128
   at Mono.Debugging.Client.Backtrace.GetFrame(Int32 index, Int32 fetchMultipleCount) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging\Mono.Debugging.Client\Backtrace.cs:line 61
   at Mono.Debugging.Client.Backtrace..ctor(IBacktrace serverBacktrace) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging\Mono.Debugging.Client\Backtrace.cs:line 27
   at Mono.Debugging.Soft.SoftDebuggerSession.HandleBreakEventSet(Event[] es, Boolean dequeuing) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2186
   at Mono.Debugging.Soft.SoftDebuggerSession.EventHandler() in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1802
```

## Configuration

**Version of the Plugin:** 2.1.3

**Platform:** Android 13.0

**Device:** Samsung SM-A528B

**Comment by smsissuechecker** [comment]
Hi @0verflux,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.
