### ISSUE TITLE
StartUpdatesAsync() - Write Not Permitted

### ISSUE THREAD

**Issue by DvD12** [dotnet-bluetooth-le/dotnet-bluetooth-le#866]
Using StartUpdatesAsync() on a characteristic with Notify property doesn't seem to work on Windows. Works fine on Android.

## Steps to reproduce

1. Run this plugin's sample project BLE.Client.WinConsole and run option 8 (Connect_Read_Services_Dispose_Loop())
![image](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/assets/7832673/c4ab0287-44a0-4909-888c-4fb197c6d7e1)

2. Step into StartUpdatesAsync() once we get to a characteristic with the Notify property

3. WriteClientCharacteristicConfigurationDescriptorWithResultAsync throws an error '[StartUpdatesNativeAsync] failed with status: ProtocolError and protocol error  Write Not Permitted'
![image](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/assets/7832673/5f38dfb1-6360-40d7-b4a2-e05dd0057122)
![image](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/assets/7832673/880cb1e3-fdf9-4aa6-b26b-016c8d82830d)

## Expected behavior
Step 2. should execute without exceptions.

## Actual behavior
Step 2. produces an exception instead.

### Crashlog

System.Exception
  HResult=0x80131500
  Message=[StartUpdatesNativeAsync] failed with status: ProtocolError and protocol error  Write Not Permitted
  Source=Plugin.BLE
  StackTrace:
   at Plugin.BLE.Extensions.GattResultExtensions.ThrowIfError(GattCommunicationStatus status, String tag, Nullable`1 protocolError) in ...\dotnet-bluetooth-le-master\Source\Plugin.BLE\Windows\Extensions\GattResultExtensions.cs:line 40
   at Plugin.BLE.Extensions.GattResultExtensions.ThrowIfError(GattWriteResult result, String tag) in ...\dotnet-bluetooth-le-master\Source\Plugin.BLE\Windows\Extensions\GattResultExtensions.cs:line 13
   at Plugin.BLE.Windows.Characteristic.<StartUpdatesNativeAsync>d__17.MoveNext() in ...\dotnet-bluetooth-le-master\Source\Plugin.BLE\Windows\Characteristic.cs:line 65
   at BLE.Client.WinConsole.PluginDemos.<Connect_Read_Services_Dispose_Loop>d__21.MoveNext() in ...\dotnet-bluetooth-le-master\Source\BLE.Client\BLE.Client.WinConsole\PluginDemos.cs:line 174

  This exception was originally thrown at this call stack:
    Plugin.BLE.Extensions.GattResultExtensions.ThrowIfError(Windows.Devices.Bluetooth.GenericAttributeProfile.GattCommunicationStatus, string, byte?) in GattResultExtensions.cs
    Plugin.BLE.Extensions.GattResultExtensions.ThrowIfError(Windows.Devices.Bluetooth.GenericAttributeProfile.GattWriteResult, string) in GattResultExtensions.cs
    Plugin.BLE.Windows.Characteristic.StartUpdatesNativeAsync(System.Threading.CancellationToken) in Characteristic.cs
    BLE.Client.WinConsole.PluginDemos.Connect_Read_Services_Dispose_Loop() in PluginDemos.cs

## Configuration

**Version of the Plugin:** 3.1.0

**Platform:** Windows 11 version 23H2 (build 22631.3593)

**Comment by smsissuechecker** [comment]
Hi @DvD12,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.
